FROM envoyproxy/envoy:v1.28-latest

# Copy certs and config (generated by `make generate`)
COPY generated/certs/ /certs/
COPY generated/envoy.json /etc/envoy/envoy.json

# Fix key permissions so envoy user can read them
RUN chmod 644 /certs/*.key

EXPOSE 443

CMD ["envoy", "-c", "/etc/envoy/envoy.json"]
