// Code generated by scripts/generate.py from domains.toml. DO NOT EDIT.

package main

// hostEnvMap maps API hosts to their environment variable names.
var hostEnvMap = map[string]string{
	"api.stripe.com": "STRIPE_API_KEY",
}
