// Code generated by adev from agent-creds.toml. DO NOT EDIT.

package main

// DomainConfig holds configuration for credential injection.
type DomainConfig struct {
	EnvVar       string
	HeaderName   string
	HeaderPrefix string
	AuthType     string
}

// domainConfigMap maps API hosts to their credential injection config.
var domainConfigMap = map[string]DomainConfig{
}
