package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// generateSandboxEnv writes generated/sandbox.env with token env vars and static env vars.
// tokens maps env var names to values (already shaped by credential type).
// staticEnv maps env var names to literal values.
func generateSandboxEnv(tokens map[string]string, staticEnv map[string]string) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by adev — do not edit\n")

	// Write token env vars in sorted order
	if len(tokens) > 0 {
		b.WriteString("\n# Credential tokens\n")
		keys := make([]string, 0, len(tokens))
		for k := range tokens {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "%s=%s\n", k, tokens[k])
		}
	}

	// Write static env vars in sorted order
	if len(staticEnv) > 0 {
		b.WriteString("\n# Static env vars from [env]\n")
		keys := make([]string, 0, len(staticEnv))
		for k := range staticEnv {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "%s=%s\n", k, staticEnv[k])
		}
	}

	// Write atomically: write to .tmp then rename
	dir := filepath.Join("generated")
	os.MkdirAll(dir, 0755)
	tmpPath := filepath.Join(dir, "sandbox.env.tmp")
	finalPath := filepath.Join(dir, "sandbox.env")

	if err := os.WriteFile(tmpPath, []byte(b.String()), 0600); err != nil {
		return fmt.Errorf("writing sandbox.env.tmp: %w", err)
	}
	if err := os.Rename(tmpPath, finalPath); err != nil {
		return fmt.Errorf("renaming sandbox.env: %w", err)
	}
	return nil
}

// shapeTokens converts a list of TokenEntry into a map of env var name → value,
// shaped by credential type from the info metadata.
func shapeTokens(entries []TokenEntry, infos map[string]*CredentialInfo) map[string]string {
	tokens := make(map[string]string)
	for _, e := range entries {
		info := infos[e.Host]
		if info == nil {
			// Fallback: use the entry's env var directly
			tokens[e.EnvVar] = e.Combined
			continue
		}
		switch info.Type {
		case "bearer":
			tokens[e.EnvVar] = e.Combined
		case "sigv4":
			tokens["AWS_ACCESS_KEY_ID"] = e.Combined
			tokens["AWS_SECRET_ACCESS_KEY"] = "placeholder"
		case "basic":
			if len(info.EnvVars) >= 2 {
				tokens[info.EnvVars[0]] = "username"
				tokens[info.EnvVars[1]] = e.Combined
			} else {
				tokens[e.EnvVar] = e.Combined
			}
		default:
			tokens[e.EnvVar] = e.Combined
		}
	}
	return tokens
}
