package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// generateSandboxEnv writes generated/sandbox.env with token env vars and static env vars.
// tokens maps env var names to values (already shaped by credential type).
// staticEnv maps env var names to literal values.
func generateSandboxEnv(tokens map[string]string, staticEnv map[string]string) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by adev — do not edit\n")

	// Write token env vars in sorted order
	if len(tokens) > 0 {
		b.WriteString("\n# Credential tokens\n")
		keys := make([]string, 0, len(tokens))
		for k := range tokens {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "%s=%s\n", k, tokens[k])
		}
	}

	// Write static env vars in sorted order
	if len(staticEnv) > 0 {
		b.WriteString("\n# Static env vars from [env]\n")
		keys := make([]string, 0, len(staticEnv))
		for k := range staticEnv {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "%s=%s\n", k, staticEnv[k])
		}
	}

	// Write atomically: write to .tmp then rename
	dir := filepath.Join("generated")
	os.MkdirAll(dir, 0755)
	tmpPath := filepath.Join(dir, "sandbox.env.tmp")
	finalPath := filepath.Join(dir, "sandbox.env")

	if err := os.WriteFile(tmpPath, []byte(b.String()), 0600); err != nil {
		return fmt.Errorf("writing sandbox.env.tmp: %w", err)
	}
	if err := os.Rename(tmpPath, finalPath); err != nil {
		return fmt.Errorf("renaming sandbox.env: %w", err)
	}
	return nil
}

// shapeTokens converts a list of TokenEntry into a map of env var name → value,
// shaped by credential type from the info metadata.
func shapeTokens(entries []TokenEntry, infos map[string]*CredentialInfo) map[string]string {
	tokens := make(map[string]string)
	for _, e := range entries {
		info := infos[e.Host]
		if info == nil {
			// Fallback: use the entry's env var directly
			tokens[e.EnvVar] = e.Combined
			continue
		}
		switch info.Type {
		case "bearer":
			tokens[e.EnvVar] = e.Combined
		case "sigv4":
			tokens["AWS_ACCESS_KEY_ID"] = e.Combined
			tokens["AWS_SECRET_ACCESS_KEY"] = "placeholder"
		case "basic":
			if len(info.EnvVars) >= 2 {
				tokens[info.EnvVars[0]] = "username"
				tokens[info.EnvVars[1]] = e.Combined
			} else {
				tokens[e.EnvVar] = e.Combined
			}
		default:
			tokens[e.EnvVar] = e.Combined
		}
	}
	return tokens
}

// resolveStaticEnv processes the [env] section from agent-creds.toml, resolving
// $secret references against the vault.yaml secrets map. Plain string values
// pass through unchanged. Returns a map of env var name → resolved value.
func resolveStaticEnv(staticEnv map[string]interface{}, vaultYAMLPath string) (map[string]string, error) {
	result := make(map[string]string)
	if len(staticEnv) == 0 {
		return result, nil
	}

	// Load secrets map from vault.yaml (only if we have $secret refs)
	var secrets map[string]map[string]string
	needSecrets := false
	for _, v := range staticEnv {
		if _, ok := v.(map[string]interface{}); ok {
			needSecrets = true
			break
		}
	}

	if needSecrets {
		data, err := os.ReadFile(vaultYAMLPath)
		if err != nil {
			return nil, fmt.Errorf("reading vault.yaml for secret resolution: %w", err)
		}
		var raw struct {
			Secrets map[string]map[string]string `yaml:"secrets"`
		}
		if err := yaml.Unmarshal(data, &raw); err != nil {
			return nil, fmt.Errorf("parsing vault.yaml secrets: %w", err)
		}
		secrets = raw.Secrets
	}

	for k, v := range staticEnv {
		switch val := v.(type) {
		case string:
			result[k] = val
		case map[string]interface{}:
			ref, ok := val["$secret"]
			if !ok {
				return nil, fmt.Errorf("env var %s: map value must have $secret key", k)
			}
			refStr, ok := ref.(string)
			if !ok {
				return nil, fmt.Errorf("env var %s: $secret value must be a string", k)
			}
			resolved, err := lookupVaultSecret(refStr, secrets)
			if err != nil {
				return nil, fmt.Errorf("env var %s: %w", k, err)
			}
			result[k] = resolved
		default:
			result[k] = fmt.Sprintf("%v", v)
		}
	}
	return result, nil
}

// lookupVaultSecret resolves a "path#KEY" reference against the secrets map.
func lookupVaultSecret(ref string, secrets map[string]map[string]string) (string, error) {
	path, key, ok := strings.Cut(ref, "#")
	if !ok {
		return "", fmt.Errorf("invalid $secret ref %q: must be path#KEY", ref)
	}
	group, exists := secrets[path]
	if !exists {
		return "", fmt.Errorf("secret group %q not found in vault.yaml", path)
	}
	val, exists := group[key]
	if !exists {
		return "", fmt.Errorf("key %q not found in secret group %q", key, path)
	}
	return val, nil
}
