package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GeneratePackagesNix generates a packages.nix file from the merged config.
// Package sets come from TOML sections like [packages], [python3Packages], etc.
// Each maps to pkgs.<name> or pkgs.<prefix>.<name> in the generated Nix.
func GeneratePackagesNix(cfg ProjectConfig, outputPath string) error {
	// Collect unique nixpkgs attributes from all package sets
	nixPkgs := make(map[string]bool)

	for prefix, pkgSet := range cfg.NixPackageSets {
		for name, enabled := range pkgSet {
			if enabled {
				if prefix == "" {
					nixPkgs[name] = true
				} else {
					nixPkgs[prefix+"."+name] = true
				}
			}
		}
	}

	// Sort for deterministic output
	var pkgList []string
	for pkg := range nixPkgs {
		pkgList = append(pkgList, pkg)
	}
	sort.Strings(pkgList)

	// Generate Nix expression
	var sb strings.Builder
	sb.WriteString("# Auto-generated by adev - do not edit\n")
	sb.WriteString("# Regenerate with: adev generate-nix\n")
	sb.WriteString("{ pkgs }:\n")
	sb.WriteString("[\n")

	for _, pkg := range pkgList {
		sb.WriteString(fmt.Sprintf("  pkgs.%s\n", pkg))
	}

	sb.WriteString("]")

	// Append inline nix expressions from plugins/agents
	for _, expr := range cfg.NixExprs {
		sb.WriteString(" ++ (\n")
		sb.WriteString("  " + strings.TrimSpace(expr) + "\n")
		sb.WriteString(")")
	}

	sb.WriteString("\n")

	// Write file
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}

func runGenerateNix(args []string) {
	workDir, _ := os.Getwd()

	// Get script dir (where agent-creds is installed)
	exe, err := os.Executable()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding executable: %v\n", err)
		os.Exit(1)
	}
	exe, _ = filepath.EvalSymlinks(exe)
	scriptDir := filepath.Dir(filepath.Dir(exe))

	// If scriptDir looks wrong (e.g., /), use workDir as fallback
	if scriptDir == "/" || scriptDir == "." {
		scriptDir = workDir
	}

	// Load config with plugins
	cfg, err := LoadProjectConfigWithPlugins(workDir, scriptDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading config: %v\n", err)
		os.Exit(1)
	}

	// Generate packages.nix in the agent-creds directory
	outputPath := filepath.Join(scriptDir, "generated", "packages.nix")
	if err := GeneratePackagesNix(cfg, outputPath); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating packages.nix: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}
