package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Package name mapping: ubuntu/debian package name -> nixpkgs attribute paths.
// Values are slices to support one-to-many mappings (e.g. build-essential -> gcc + gnumake).
// Empty slice means the package is satisfied another way (built-in or not needed in Nix).
var packageMap = map[string][]string{
	// Languages
	"python3":           {"python3"},
	"python3-pip":       {"python3Packages.pip"},
	"python3-venv":      {},  // venv is part of python, not separate
	"python-is-python3": {},  // not needed in nix
	"nodejs":            {"nodejs"},
	"npm":               {},  // comes with nodejs
	"go":                {"go"},
	"rustup":            {"rustup"},

	// CLI tools
	"ripgrep":  {"ripgrep"},
	"fd-find":  {"fd"},
	"bat":      {"bat"},
	"eza":      {"eza"},
	"fzf":      {"fzf"},
	"jq":       {"jq"},
	"httpie":   {"httpie"},
	"tree":     {"tree"},
	"unzip":    {"unzip"},
	"neovim":   {"neovim"},
	"tmux":     {"tmux"},

	// Build tools — build-essential maps to the full Nix toolchain equivalent
	"build-essential":      {"gcc", "gnumake", "binutils"},
	"gnumake":              {"gnumake"},
	"libcurl4-openssl-dev": {"curl.dev"},
	"libssl-dev":           {"openssl.dev"},
	"zlib1g-dev":           {"zlib.dev"},

	// Base utilities (these are also in flake.nix basePackages, but listing here
	// ensures they appear in packages.nix when requested by plugins)
	"curl":            {"curl"},
	"wget":            {"wget"},
	"git":             {"git"},
	"ca-certificates": {"cacert"},
	"sudo":            {"sudo"},
	"socat":           {"socat"},
	"dnsutils":        {"dnsutils"},
	"file":            {"file"},

	// Agent packages
	"claude-code": {"claude-code"}, // native binary via overlay in flake.nix
}

// GeneratePackagesNix generates a packages.nix file from the merged config.
func GeneratePackagesNix(cfg ProjectConfig, outputPath string) error {
	// Collect unique nixpkgs attributes
	nixPkgs := make(map[string]bool)

	for _, pkg := range cfg.Packages {
		nixAttrs, ok := packageMap[pkg]
		if !ok {
			fmt.Fprintf(os.Stderr, "Warning: unknown package %q, skipping\n", pkg)
			continue
		}
		for _, attr := range nixAttrs {
			nixPkgs[attr] = true
		}
	}

	// Sort for deterministic output
	var pkgList []string
	for pkg := range nixPkgs {
		pkgList = append(pkgList, pkg)
	}
	sort.Strings(pkgList)

	// Generate Nix expression
	var sb strings.Builder
	sb.WriteString("# Auto-generated by adev - do not edit\n")
	sb.WriteString("# Regenerate with: adev generate-nix\n")
	sb.WriteString("{ pkgs }:\n")
	sb.WriteString("[\n")

	for _, pkg := range pkgList {
		sb.WriteString(fmt.Sprintf("  pkgs.%s\n", pkg))
	}

	sb.WriteString("]")

	// Append inline nix expressions from plugins/agents
	for _, expr := range cfg.NixExprs {
		sb.WriteString(" ++ (\n")
		sb.WriteString("  " + strings.TrimSpace(expr) + "\n")
		sb.WriteString(")")
	}

	sb.WriteString("\n")

	// Write file
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}

func runGenerateNix(args []string) {
	workDir, _ := os.Getwd()

	// Get script dir (where agent-creds is installed)
	exe, err := os.Executable()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding executable: %v\n", err)
		os.Exit(1)
	}
	exe, _ = filepath.EvalSymlinks(exe)
	scriptDir := filepath.Dir(filepath.Dir(exe))

	// If scriptDir looks wrong (e.g., /), use workDir as fallback
	if scriptDir == "/" || scriptDir == "." {
		scriptDir = workDir
	}

	// Load config with plugins
	cfg, err := LoadProjectConfigWithPlugins(workDir, scriptDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading config: %v\n", err)
		os.Exit(1)
	}

	// Generate packages.nix in the agent-creds directory
	outputPath := filepath.Join(scriptDir, "generated", "packages.nix")
	if err := GeneratePackagesNix(cfg, outputPath); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating packages.nix: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
	fmt.Printf("Packages: %v\n", cfg.Packages)
}
