package main

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// SkillConfig registers one named Agent Skill stored in a Git repository.
// Ref is a Git ref or revision, and Path selects a skill within a monorepo.
// Nix has the same meaning as it does for plugins: an optional list of
// packages needed by the skill.
type SkillConfig struct {
	Name        string `toml:"name"`
	Description string `toml:"description"`
	Repo        string `toml:"repo"`
	Ref         string `toml:"ref"`
	Path        string `toml:"path"`
	Nix         string `toml:"nix"`
}

var (
	skillNameRE = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$`)
	skillPathRE = regexp.MustCompile(`^[A-Za-z0-9._/-]+$`)
	gitRevRE    = regexp.MustCompile(`^[0-9a-fA-F]{40}$`)
)

func (s SkillConfig) sourcePath() string {
	if s.Path == "" {
		return "."
	}
	return s.Path
}

// Validate checks the provider-neutral registration.
func (s SkillConfig) Validate() error {
	if !skillNameRE.MatchString(s.Name) {
		return fmt.Errorf("name %q must contain lowercase letters, digits, and hyphens", s.Name)
	}
	parsed, err := url.Parse(s.Repo)
	if err != nil || parsed.Scheme == "" {
		return fmt.Errorf("skill %q: repo %q must be a Git URL", s.Name, s.Repo)
	}
	if parsed.Fragment != "" {
		return fmt.Errorf("skill %q: repo %q must not contain a URL fragment", s.Name, s.Repo)
	}
	switch parsed.Scheme {
	case "https", "http", "ssh", "git":
		if parsed.Host == "" {
			return fmt.Errorf("skill %q: repo %q must include a host", s.Name, s.Repo)
		}
	case "file":
		if !filepath.IsAbs(parsed.Path) {
			return fmt.Errorf("skill %q: file repo %q must be absolute", s.Name, s.Repo)
		}
	default:
		return fmt.Errorf("skill %q: repo %q uses unsupported URL scheme %q", s.Name, s.Repo, parsed.Scheme)
	}
	if s.Ref == "" || strings.TrimSpace(s.Ref) != s.Ref || strings.ContainsAny(s.Ref, "\x00\r\n") {
		return fmt.Errorf("skill %q: ref must be a non-empty Git ref without surrounding whitespace", s.Name)
	}
	if err := validateRelativeSkillPath("path", s.sourcePath(), true); err != nil {
		return fmt.Errorf("skill %q: %w", s.Name, err)
	}
	return nil
}

func validateRelativeSkillPath(field, path string, allowDot bool) error {
	if path == "" || filepath.IsAbs(path) || !skillPathRE.MatchString(path) {
		return fmt.Errorf("%s %q must be a relative directory", field, path)
	}
	clean := filepath.Clean(path)
	if clean != path || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return fmt.Errorf("%s %q must be a clean relative directory", field, path)
	}
	if !allowDot && clean == "." {
		return fmt.Errorf("%s must name a directory below the agent home", field)
	}
	return nil
}

// ResolveSkills replaces requested names with their scoped registrations and
// merges each selected skill's optional Nix packages into the environment.
func ResolveSkills(cfg *ProjectConfig, discovered map[string]string) error {
	seen := make(map[string]bool)
	for _, name := range cfg.SkillNames {
		if seen[name] {
			continue
		}
		path, ok := discovered[name]
		if !ok {
			return fmt.Errorf("skill %q not found", name)
		}
		skill, err := LoadSkill(path)
		if err != nil {
			return fmt.Errorf("loading skill %s: %w", name, err)
		}
		if skill.Name != name {
			return fmt.Errorf("loading skill %s: registration name is %q", name, skill.Name)
		}
		if cfg.Skills == nil {
			cfg.Skills = make(map[string]SkillConfig)
		}
		cfg.Skills[name] = skill
		if nix := strings.TrimSpace(skill.Nix); nix != "" {
			cfg.NixExprs = append(cfg.NixExprs, nix)
		}
		seen[name] = true
	}
	if len(cfg.Skills) == 0 {
		return nil
	}
	if cfg.SkillDir == "" {
		return fmt.Errorf("agent %q does not define skill_dir", cfg.Sandbox.Agent)
	}
	if err := validateRelativeSkillPath("skill_dir", cfg.SkillDir, false); err != nil {
		return fmt.Errorf("agent %q: %w", cfg.Sandbox.Agent, err)
	}
	return nil
}

// GenerateSkillsNix writes the provider-neutral skill source location. The
// final harness layer consumes this derivation and owns provider-specific
// setup.
func GenerateSkillsNix(cfg ProjectConfig, outputPath string) error {
	contents := renderSkillsNix(cfg)
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(contents), 0644)
}

func renderSkillsNix(cfg ProjectConfig) string {
	var names []string
	for name := range cfg.Skills {
		names = append(names, name)
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("# Auto-generated by adev - do not edit\n")
	sb.WriteString("{ pkgs }:\n")
	sb.WriteString("pkgs.runCommand \"sandbox-skills\" {} ''\n")
	sb.WriteString("  mkdir -p \"$out/skills\"\n")
	for _, name := range names {
		skill := cfg.Skills[name]
		sb.WriteString(fmt.Sprintf("  mkdir -p \"$out/skills/%s\"\n", name))
		sb.WriteString("  cp -R \"")
		sb.WriteString("${builtins.fetchGit { url = ")
		sb.WriteString(nixString(skill.Repo))
		if gitRevRE.MatchString(skill.Ref) {
			sb.WriteString("; rev = ")
			sb.WriteString(nixString(strings.ToLower(skill.Ref)))
		} else {
			sb.WriteString("; ref = ")
			sb.WriteString(nixString(skill.Ref))
		}
		sb.WriteString("; }}")
		if skill.sourcePath() != "." {
			sb.WriteString("/")
			sb.WriteString(skill.sourcePath())
		}
		sb.WriteString("/.\" \"$out/skills/")
		sb.WriteString(name)
		sb.WriteString("/\"\n")
		sb.WriteString(fmt.Sprintf("  test -f \"$out/skills/%s/SKILL.md\"\n", name))
	}
	sb.WriteString("''\n")
	return sb.String()
}

// GenerateHarnessNix writes the final, harness-specific layer. It intentionally
// comes after plugins and neutral skill fetching and copies from the stable
// skill location into the selected harness's native directory.
func GenerateHarnessNix(cfg ProjectConfig, outputPath string) error {
	contents := renderHarnessNix(cfg)
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(contents), 0644)
}

func renderHarnessNix(cfg ProjectConfig) string {
	var names []string
	for name := range cfg.Skills {
		names = append(names, name)
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("# Auto-generated by adev - do not edit\n")
	sb.WriteString("{ pkgs, skills }:\n")
	sb.WriteString("pkgs.runCommand \"sandbox-harness\" {} ''\n")
	sb.WriteString("  mkdir -p \"$out/home\"\n")
	for _, name := range names {
		target := filepath.ToSlash(filepath.Join(cfg.SkillDir, name))
		sb.WriteString(fmt.Sprintf("  mkdir -p \"$out/home/%s\"\n", target))
		sb.WriteString(fmt.Sprintf(
			"  cp -R \"${skills}/skills/%s/.\" \"$out/home/%s/\"\n",
			name, target,
		))
		sb.WriteString(fmt.Sprintf("  test -f \"$out/home/%s/SKILL.md\"\n", target))
	}
	sb.WriteString("''\n")
	return sb.String()
}

func nixString(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"${", `\${`,
		"\n", `\n`,
		"\r", `\r`,
		"\t", `\t`,
	)
	return `"` + replacer.Replace(value) + `"`
}

type skillMount struct {
	source string
	target string
}

func sandboxHarnessLayerDir(envPath string) (string, error) {
	store, err := sandboxEnvPrivateStore(envPath)
	if err != nil {
		return "", err
	}
	layer := filepath.Join(filepath.Dir(filepath.Dir(store)), "harness-layer")
	if info, err := os.Stat(layer); err != nil || !info.IsDir() {
		return "", fmt.Errorf("sandbox harness layer is unavailable: %s", layer)
	}
	return layer, nil
}

func sandboxSkillsAvailable(cfg ProjectConfig, envPath string) bool {
	if len(cfg.Skills) == 0 {
		return true
	}
	layer, err := sandboxHarnessLayerDir(envPath)
	if err != nil {
		return false
	}
	for name := range cfg.Skills {
		if !fileExists(filepath.Join(layer, cfg.SkillDir, name, "SKILL.md")) {
			return false
		}
	}
	return true
}

func prepareSkillMounts(
	cfg ProjectConfig, envPath, homeDir string, state agentState,
) ([]skillMount, error) {
	if len(cfg.Skills) == 0 {
		return nil, nil
	}
	layer, err := sandboxHarnessLayerDir(envPath)
	if err != nil {
		return nil, err
	}
	var names []string
	for name := range cfg.Skills {
		names = append(names, name)
	}
	sort.Strings(names)
	mounts := make([]skillMount, 0, len(names))
	for _, name := range names {
		source := filepath.Join(layer, cfg.SkillDir, name)
		if !fileExists(filepath.Join(source, "SKILL.md")) {
			return nil, fmt.Errorf("skill %q is missing from sandbox harness layer", name)
		}
		target := filepath.Join(homeDir, cfg.SkillDir, name)
		if err := state.ensureTargetDirectory(target); err != nil {
			return nil, fmt.Errorf("preparing skill %q: %w", name, err)
		}
		mounts = append(mounts, skillMount{source: source, target: target})
	}
	return mounts, nil
}

func skillDockerArgs(mounts []skillMount) []string {
	args := make([]string, 0, len(mounts)*2)
	for _, mount := range mounts {
		args = append(args, "-v", mount.source+":"+mount.target+":ro")
	}
	return args
}

func skillBwrapArgs(mounts []skillMount) []string {
	args := make([]string, 0, len(mounts)*3)
	for _, mount := range mounts {
		args = append(args, "--ro-bind", mount.source, mount.target)
	}
	return args
}
